// pt-BR seeding pipeline. Subcommands:
//   node scripts/ptbr_seed.mjs tsv            > scripts/i18n_ptbr_review.tsv
//     (merges buildRows() es-MX with scripts/i18n_ptbr_draft.json → review TSV)
//   node scripts/ptbr_seed.mjs import <tsv>   > scripts/i18n_seed_ptbr.sql
//   node scripts/ptbr_seed.mjs coverage       (compares DB pt-BR keys vs buildRows keys)
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { buildRows } from './extract_translations.mjs';

const TAB = '\t';
const escTsvCell = (s) => String(s ?? '').replace(/\\/g, '\\\\').replace(/\t/g, '\\t').replace(/\r?\n/g, '\\n');
const unescTsvCell = (s) => String(s ?? '').replace(/\\n/g, '\n').replace(/\\t/g, '\t').replace(/\\\\/g, '\\');

export function rowsToTsv(rows) {
  const header = ['key', 'domain', 'es_mx', 'pt_br'].join(TAB);
  const lines = rows.map(r => [r.key, r.domain, escTsvCell(r.es_mx), escTsvCell(r.pt_br)].join(TAB));
  return [header, ...lines].join('\n') + '\n';
}

export function parseTsv(tsv) {
  const lines = tsv.split('\n').filter(l => l.length);
  const [, ...body] = lines; // drop header
  return body.map(line => {
    const [key, domain, es_mx, pt_br] = line.split(TAB);
    return { key, domain, es_mx: unescTsvCell(es_mx), pt_br: unescTsvCell(pt_br) };
  });
}

export const esc = (v) => v === null || v === undefined ? 'NULL' : "'" + String(v).replace(/'/g, "''") + "'";

export function emitSql(rows) {
  const out = [];
  out.push('-- pt-BR seed (generated by ptbr_seed.mjs import)');
  out.push(`-- rows: ${rows.length}`);
  out.push('BEGIN;');
  const CHUNK = 100;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const slice = rows.slice(i, i + CHUNK);
    out.push('INSERT INTO public.translations (key, lang, text, domain) VALUES');
    out.push(slice.map((r, j) =>
      `  (${esc(r.key)}, 'pt-BR', ${esc(r.pt_br)}, ${esc(r.domain)})${j === slice.length - 1 ? '' : ','}`
    ).join('\n'));
    out.push('ON CONFLICT (key, lang) DO NOTHING;');
  }
  out.push('COMMIT;');
  return out.join('\n') + '\n';
}

async function main() {
  const [cmd, arg] = process.argv.slice(2);
  if (cmd === 'tsv') {
    const es = buildRows().filter(r => r.lang === 'es-MX');
    let draft = {};
    try { draft = JSON.parse(await readFile(new URL('./i18n_ptbr_draft.json', import.meta.url), 'utf8')); } catch {}
    const rows = es.map(r => ({ key: r.key, domain: r.domain, es_mx: r.text, pt_br: draft[r.key] ?? '' }));
    process.stdout.write(rowsToTsv(rows));
  } else if (cmd === 'import') {
    const tsv = await readFile(arg, 'utf8');
    const rows = parseTsv(tsv).filter(r => r.pt_br && r.pt_br.trim());
    process.stdout.write(emitSql(rows));
  } else if (cmd === 'coverage') {
    const { SUPABASE_URL, SUPABASE_ANON_KEY } = await import('../public/js/config.js');
    const want = new Set(buildRows().filter(r => r.lang === 'es-MX').map(r => r.key));
    const res = await fetch(`${SUPABASE_URL}/rest/v1/translations?lang=eq.pt-BR&select=key`, {
      headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}` },
    });
    const have = new Set((await res.json()).map(r => r.key));
    let missing = 0, extra = 0;
    for (const k of want) if (!have.has(k)) { missing++; console.log('MISSING pt-BR:', k); }
    for (const k of have) if (!want.has(k)) { extra++; console.log('EXTRA pt-BR:', k); }
    console.log(`pt-BR coverage: ${want.size} expected, ${have.size} in DB | missing=${missing} extra=${extra}`);
    process.exit(missing + extra === 0 ? 0 : 1);
  } else {
    console.error('usage: ptbr_seed.mjs tsv | import <tsv> | coverage');
    process.exit(2);
  }
}
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) main();
